### ISSUE TITLE
Add Admin Page

### ISSUE THREAD

**Issue by jp-quintana** [jp-quintana/react-shopping-cart#59]
# Tasks
Add admin panel and feature for admin to add/delete/edit products.

## Admin Page UI
 - [x] Add admin panel.
 - [x] Add create/edit product page.

## useAdmin Hook
 - [x] Create hook containing all admin functions.

## Admin Logic
 - [x] Incorporate Admin logic.
